

services:
  redis:
    image: redis:8.0.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - redis_data:/data
    networks:
      - articlenetwork
    restart: unless-stopped

volumes:
  redis_data:
networks:
  articlenetwork:
    external: true
    name: articlenetwork
