# Build aþamasý
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .

RUN dotnet restore PArticle.CategorySubscriber/PArticle.CategorySubscriber.csproj
RUN dotnet publish PArticle.CategorySubscriber/PArticle.CategorySubscriber.csproj -c Release -o /app/publish

# Runtime aþamasý
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "PArticle.CategorySubscriber.dll"]
#docker build -t particle-subscribers-category -f Dockerfile_Category .
#docker run --name categorysubscriber --network articlenetwork particle-subscribers-category