# Build aþamasý
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY . .

RUN dotnet restore PArticle.TagSubscriber/PArticle.TagSubscriber.csproj
RUN dotnet publish PArticle.TagSubscriber/PArticle.TagSubscriber.csproj -c Release -o /app/publish

# Runtime aþamasý
FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "PArticle.TagSubscriber.dll"]
#docker build -t particle-subscribers-tag -f Dockerfile_Tag .
#docker run --name tagsubscriber --network articlenetwork particle-subscribers-tag